### PR TITLE
change to Object.Equals

### PR DESCRIPTION
**Pull request by ortrails**
Bogdan's suggestion seems to work and it run about twice as fast as doing a string comparison.

### CODE REVIEW

**Comment by upta** [comment]
I'm all for this on principle, but it seems that it failed the appveyor build/can't auto merge.  If you want to get that sorted out I'll be happy to include/update nuget.  Thanks!

**Comment by ortrails** [comment]
Probably because there was a commit in between. I'll take a look.

**Comment by upta** [comment]
That's what I was thinking, too.  Sounds good, thanks!

**Comment by ortrails** [comment]
It seems to have been failing due to broken unit tests. I cleaned that up and it seems to be ready now.

**Comment by upta** [comment]
Sorry, I totally forgot that you'd submitted this!  Will see about getting Nuget updated tomorrow.  Thanks!

**Comment by ortrails** [comment]
No problem, I figured you would get to it eventually.

**Pull request merged**
