### PR TITLE
Add SubscribeTask, PublishAsync

### PR DESCRIPTION
**Pull request by TomaszStanisz**

### CODE REVIEW

**Comment by upta** [comment]
Curious, what would the benefits be over simply switching it to be Task-based like I did in my async-test branch?

https://github.com/upta/pubsub/tree/async-test

I originally went down the path of doing separate [Method]Async calls, but since the whole goal of the library is to keep things simple I was wary of doing so and didn't see a benefit.

I could be wrong and there is one, of course :)  I'm just not seeing it.

**Comment by TomaszStanisz** [comment]
Hi Brian,

Sorry for delay but I was busy and later I just forgot to answer 😊
I also didn’t check you second brunch before my changes (now I checked), but I still think that subscription with Task option and Publish which return Task can be useful.

The reasons why I add this task base methods is because:

  1.  I already have methods which returns tasks and I want to subscribe with this methods. I know that I can create another void method and call Task.Run inside but it is more comfortable to have dedicated method.
  2.  When you have both versions for publish (which return void or Task) and both version for subscribe (action and function with Task) then you can use it in all scenarios which you need:

  *   Publish and do not wait for any subscriber (doesn’t matter if it is subscribed with action or task). You can just call PublishAsync without await
  *   Publish and wait for all subscribers (doesn’t matter if it is subscribed with action or task). You can just call await PublishAsync.
  *   Publish and wait for all subscribers subscribed with actions and don’t wait for subscribers subscribed with tasks. You can just call Publish.
  *   Subscribe with action or with Task (depends from your needs)
Br
Tomasz


Od: Brian <notifications@github.com>
Wysłano: 26 March 2019 22:04
Do: upta/pubsub <pubsub@noreply.github.com>
DW: Tomasz Stanisz <tomasz.stanisz@novacura.com>; Author <author@noreply.github.com>
Temat: Re: [upta/pubsub] Add SubscribeTask, PublishAsync (#20)


Curious, what would the benefits be over simply switching it to be Task-based like I did in my async-test branch?

https://github.com/upta/pubsub/tree/async-test

I originally went down the path of doing separate [Method]Async calls, but since the whole goal of the library is to keep things simple I was wary of doing so and didn't see a benefit.

I could be wrong and there is one, of course :) I'm just not seeing it.

**Comment by fabricioferreira** [comment]
@upta I was about to implement this wrapper myself when I saw this PR.
Are there any plans to merge it and to make it official?

Thanks!

**Comment by upta** [comment]
@TomaszStanisz @fabricioferreira I'll be honest, I completely forgot about this.  My apologies!

Looking back over it I'm fine with it with the changes.  The only minor thing I think would be better would be to change the SubscribeTask methods to simply be called Subscribe; no reason they can't simply be an overload of the method and cleans up the public-facing surface a bit.

**Comment by TomaszStanisz** [comment]
No problem for me, I changed method name

**Comment by fabricioferreira** [comment]
The solution sound good to me.
Looking forward for this merge @TomaszStanisz @upta .
Thanks!!

**Comment by upta** [comment]
I'll get it merged and updated on nuget :). Been a bit swamped lately, but I'll try to do so in the next couple of days.

Thanks!
________________________________

**Comment by upta** [comment]
Finally managed to remember long enough and carve out enough time to get this updated ;)  It's been merged into master and published on Nuget a 3.1.0.

Thanks!

**Pull request merged**
