### PR TITLE
Bugfix for exception in a race state. Simplification of the library by removing the ioc stuff.

### PR DESCRIPTION
**Pull request by Bebu1985**
Hello upta,

I prepared this pull request, after some problems with the library. There was a state, in which the handler list was changed, while a enumeration was running. That resulted in an exception.

Also after reading #25, i retought the ioc stuff i submitted earlier and removed it completly. Now there is only one interface for the hub, it is still ioc friendly, but much simpler.

Please have a look and let me know, what you think.

Greetings Bebu1985

### CODE REVIEW

**Comment by gb0o** [comment]
I came across the same problem. Changing the handlers list while iterating generates an exception:
```
    System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
      at at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
      at at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
      at at System.Collections.Generic.List`1.Enumerator.MoveNext()
      at at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
      at at PubSub.Hub.Publish[T](T data)
```
It can be reproduced when publishing an event that is handled by an object that itself creates a handler. The simple fix is returning list which is not modified by creation of new handlers, as you have implemented in this PR.

I wrote a unit test to verify it is fixed. Maybe this could be added to `CoreHubTests`.
```
        [TestMethod]
        public void Publish_NoExceptionRaisedWhenHandlerCreatesNewSubscriber()
        {
            // arrange
            _hub.Subscribe(new Action<Event>(a => new Stuff(_hub)));

            // act
            try
            {
                _hub.Publish(new Event());
            }

            // assert
            catch (InvalidOperationException e)
            {
                Assert.Fail($"Expected no exception, but got: {e}");
            }
        }

        internal class Stuff
        {
            public Stuff(Hub hub)
            {
                hub.Subscribe(new Action<Event>(a => { }));
            }
        }
```

Regards,
Guy

**Comment by Bebu1985** [comment]
I gladly integrate your unittest in my pull request. But it needs some time, i am busy until next Monday.

**Comment by gb0o** [comment]
No worries, I'm not in a hurry to integrate a new version of `pubsub`. The older version works well enough. I was interested in testing if the new Async methods can improve UI responsiveness before I ran into this bug.

**Comment by Bebu1985** [comment]
The unittest is integrated.

**Comment by gb0o** [comment]
Hi @Bebu1985. This PR contains both a bug fix and alot of refactoring. It might be worth splitting the PR into two - one for the bug fix and the other for refactoring. Then if there is any problem accepting refactoring changes the bug fix can still be approved separately. It would be good to have the bug fix merged because issue #30 looks alot like the same problem. @upta does that make sense to you?

**Comment by upta** [comment]
@gb0o @Bebu1985 I'd agree with splitting it out a bit, especially so we can easily get that bug fixed.

From what I can see, it seems like this PR:

- Potentially fixes the bug from #30 
- Does a bunch of refactoring
- Adds an Azure Pipelines build definition (which I'm not strictly opposed to, but there is already an AppVeyor one so not really pressing)
- Updates the major version

Quite a few separate things (none of them bad at all) for a single PR :)

**Comment by Bebu1985** [comment]
I submitted a new pull request with only the bugfix and the unittest.

**Comment by upta** [comment]
Closing this since the current state has conflicts and the key bits were done in #31

**Pull request closed without merging**
