### PR TITLE
Updated pubsub to .net standard 1.5

### PR DESCRIPTION
**Pull request by Macjon**
I've updated the project to .net standard 1.5.

### CODE REVIEW

**Comment by upta** [comment]
Looks like the formatting in the hub class got jacked up; if there aren't any significant changes to it, maybe just roll back the changes to that file.  Otherwise, not opposed to merging, thanks!

**Comment by Macjon** [comment]
There is one change at line 43 of the Hub.cs file.

**Comment by upta** [comment]
I pulled down this branch locally and (in VS 2017 at least, haven't tried elsewhere) the tests won't run.  Possible that something needs to be updated in that project as well?

**Comment by dazinator** [comment]
I have fixed this up: https://github.com/dazinator/pubsub/tree/netstandard

**Comment by dazinator** [comment]
I'll need to add some attributes to the project control the nuspec that is produced when you do a `Pack`

**Comment by upta** [comment]
@dazinator Great!  If you want to just submit yours as another PR when you're done I'll be happy to merge that one instead.

**Comment by dazinator** [comment]
PR Submitted.

**Pull request merged**
